# Messier package
# This will include extra details on Messier objects that can be used for
# displaying in the reports


class MessierData:
    def __init__(self):
        self.object_type = {'m1': 'Supernova remnant',
                            'm2': 'Globular cluster',
                            'm3': 'Globular cluster',
                            'm4': 'Globular cluster',
                            'm5': 'Globular cluster',
                            'm6': 'Open cluster',
                            'm7': 'Open cluster',
                            'm8': 'Nebula with cluster',
                            'm9': 'Globular cluster',
                            'm10': 'Globular cluster',
                            'm11': 'Open cluster',
                            'm12': 'Globular cluster',
                            'm13': 'Globular cluster',
                            'm14': 'Globular cluster',
                            'm15': 'Globular cluster',
                            'm16': 'H II region nebula with cluster',
                            'm17': 'H II region nebula with cluster',
                            'm18': 'Open cluster',
                            'm19': 'Globular cluster',
                            'm20': 'H II region nebula with cluster',
                            'm21': 'Open cluster',
                            'm22': 'Globular cluster',
                            'm23': 'Open cluster',
                            'm24': 'Milky Way star cloud',
                            'm25': 'Open cluster',
                            'm26': 'Open cluster',
                            'm27': 'Planetary nebula',
                            'm28': 'Globular cluster',
                            'm29': 'Open cluster',
                            'm30': 'Globular cluster',
                            'm31': 'Spiral galaxy',
                            'm32': 'Dwarf elliptical galaxy',
                            'm33': 'Spiral galaxy',
                            'm34': 'Open cluster',
                            'm35': 'Open cluster',
                            'm36': 'Open cluster',
                            'm37': 'Open cluster',
                            'm38': 'Open cluster',
                            'm39': 'Open cluster',
                            'm40': 'Double star',
                            'm41': 'Open cluster',
                            'm42': 'H II region nebula',
                            'm43': 'H II region nebula (part of the Orion Nebula)',
                            'm44': 'Open cluster',
                            'm45': 'Open cluster',
                            'm46': 'Open cluster',
                            'm47': 'Open cluster',
                            'm48': 'Open cluster',
                            'm49': 'Elliptical galaxy',
                            'm50': 'Open cluster',
                            'm51': 'Spiral galaxy',
                            'm52': 'Open cluster',
                            'm53': 'Globular cluster',
                            'm54': 'Globular cluster',
                            'm55': 'Globular cluster',
                            'm56': 'Globular cluster',
                            'm57': 'Planetary nebula',
                            'm58': 'Barred Spiral galaxy',
                            'm59': 'Elliptical galaxy',
                            'm60': 'Elliptical galaxy',
                            'm61': 'Spiral galaxy',
                            'm62': 'Globular cluster',
                            'm63': 'Spiral galaxy',
                            'm64': 'Spiral galaxy',
                            'm65': 'Barred Spiral galaxy',
                            'm66': 'Barred Spiral galaxy',
                            'm67': 'Open cluster',
                            'm68': 'Globular cluster',
                            'm69': 'Globular cluster',
                            'm70': 'Globular cluster',
                            'm71': 'Globular cluster',
                            'm72': 'Globular cluster',
                            'm73': 'Asterism',
                            'm74': 'Spiral galaxy',
                            'm75': 'Globular cluster',
                            'm76': 'Planetary nebula',
                            'm77': 'Spiral galaxy',
                            'm78': 'Diffuse nebula',
                            'm79': 'Globular cluster',
                            'm80': 'Globular cluster',
                            'm81': 'Spiral galaxy',
                            'm82': 'Starburst galaxy',
                            'm83': 'Barred Spiral galaxy',
                            'm84': 'Lenticular galaxy',
                            'm85': 'Lenticular galaxy',
                            'm86': 'Lenticular galaxy',
                            'm87': 'Elliptical galaxy',
                            'm88': 'Spiral galaxy',
                            'm89': 'Elliptical galaxy',
                            'm90': 'Spiral galaxy',
                            'm91': 'Barred Spiral galaxy',
                            'm92': 'Globular cluster',
                            'm93': 'Open cluster',
                            'm94': 'Spiral galaxy',
                            'm95': 'Barred Spiral galaxy',
                            'm96': 'Spiral galaxy',
                            'm97': 'Planetary nebula',
                            'm98': 'Spiral galaxy',
                            'm99': 'Spiral galaxy',
                            'm100': 'Spiral galaxy',
                            'm101': 'Spiral galaxy',
                            'm102': 'Lenticular galaxy',
                            'm103': 'Open cluster',
                            'm104': 'Spiral galaxy',
                            'm105': 'Elliptical galaxy',
                            'm106': 'Spiral galaxy',
                            'm107': 'Globular cluster',
                            'm108': 'Barred Spiral galaxy',
                            'm109': 'Barred Spiral galaxy',
                            'm110': 'Dwarf elliptical galaxy'}

        self.messier_filters = {'m1': 'UHC/DEEP-SKY (H-beta *not* recommended).',
                                'm8': 'UHC/OIII',
                                'm16': 'UHC/OIII, but H-BETA hurts the view',
                                'm17': 'OIII/UHC (H-BETA not recommended)',
                                'm20': 'UHC/H-BETA',
                                'm27': 'UHC (OIII also useful in showing some inner detail, but H-BETA is NOT '
                                       'recommended)',
                                'm42': 'UHC/OIII (near-tie)*',
                                'm43': 'H-BETA (UHC and Deep-Sky also help)',
                                'm57': 'UHC/OIII. Nebula is bright and small enough not to really benefit enormously '
                                       'from filter use, but UHC does improve it to a degree (H-BETA is NOT '
                                       'recommended!)',
                                'm76': 'UHC/OIII (H-BETA NOT recommended!)',
                                'm97': 'OIII/UHC (H-beta *not* recommended)'}

        self.messier_images = {'m1': 'https://www.nasa.gov/sites/default/files/styles/full_width/public/thumbnails'
                                     '/image/crab-nebula-mosaic.jpg?itok=DNaRmPtc',
                               'm2': 'https://www.nasa.gov/sites/default/files/styles/full_width/public/thumbnails'
                                     '/image/m2.jpg?itok=wm6A_ELC'
        }


    def return_object(self):
        return self.object_type

    def return_filters(self):
        return self.messier_filters
